events {}

http {
    upstream fastapi_app {
        server fastapi:8000;
    }

    upstream flask_app {
        server flask:5000;
    }

    server {
        listen 80;

         location /loaderio-e01b8b318c48a61249f84ee82940c95e/ {
            return 200 'loaderio-e01b8b318c48a61249f84ee82940c95e';
            add_header Content-Type text/plain;
        }

        location /fastapi/ {
            proxy_pass http://fastapi_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /flask/ {
            proxy_pass http://flask_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}